data:
  raw_data_path: data/raw/
  processed_data_path: data/processed/
  external_data_path: data/external/

model:
  type: LSTM  # or Transformer, RNN, etc.
  embedding_dim: 128
  hidden_dim: 256
  num_layers: 2

training:
  batch_size: 32
  epochs: 10
  learning_rate: 0.001

paths:
  saved_model_dir: saved_models/
  figures_dir: reports/figures/
  results_file: reports/results.md
